spring.application.name=elearning

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/bibo?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate

# ===============================
# JWT
# ===============================
app.jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
app.jwt.access-token-expiration=3600000

# ===============================
# LOGGING (OPTIONAL)
# ===============================
logging.level.org.springframework.security=DEBUG

groq.api.key=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