ALTER TABLE users ADD COLUMN first_name VARCHAR(100);
ALTER TABLE users ADD COLUMN last_name VARCHAR(100);
ALTER TABLE users ADD COLUMN age INT;
ALTER TABLE users ADD COLUMN grade VARCHAR(50);
ALTER TABLE users ADD COLUMN school VARCHAR(150);